//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IAskMeWeb")]
public interface IAskMeWeb {

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAskMeWeb/GetContentList", ReplyAction = "http://tempuri.org/IAskMeWeb/GetContentListResponse")]
  string GetContentList();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAskMeWeb/GetContentList", ReplyAction = "http://tempuri.org/IAskMeWeb/GetContentListResponse")]
  System.Threading.Tasks.Task<string> GetContentListAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAskMeWebChannel : IAskMeWeb, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AskMeWebClient : System.ServiceModel.ClientBase<IAskMeWeb>, IAskMeWeb {

  public AskMeWebClient() {
  }

  public AskMeWebClient(string endpointConfigurationName) :
          base(endpointConfigurationName) {
  }

  public AskMeWebClient(string endpointConfigurationName, string remoteAddress) :
          base(endpointConfigurationName, remoteAddress) {
  }

  public AskMeWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
          base(endpointConfigurationName, remoteAddress) {
  }

  public AskMeWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
          base(binding, remoteAddress) {
  }

  public string GetContentList() {
    return base.Channel.GetContentList();
  }

  public System.Threading.Tasks.Task<string> GetContentListAsync() {
    return base.Channel.GetContentListAsync();
  }
}
